---
- name: Install Nginx
  package:
    name: "{{ package }}"
    state: present
  with_items: "{{ nginx_packages }}"
  loop_control:
    loop_var: package
  register: _install_nginx
  until: _install_nginx is success
  retries: 3
  delay: 2

- name: Remove Nginx default site file
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Copy the Jumpserver site file
  template:
    src: jumpserver.conf.j2
    dest: /etc/nginx/conf.d/jumpserver.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart Nginx

- name: Ensure Nginx is started and enabled on boot
  service:
    name: nginx
    state: started
    enabled: yes