---
- name: Stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Disable selinux at next reboot
  selinux:
    state: disabled

- name: Set selinux in permissive mode until the machine is rebooted
  shell: setenforce 0 || true
  ignore_errors: true
  changed_when: false

- name: Install basic dependencies
  package:
    name: "{{ package }}"
    state: present
  register: _install_dep_packages
  until: _install_dep_packages is success
  retries: 3
  delay: 2
  with_items: "{{ basic_dependencies }}"
  loop_control:
    loop_var: package